module.exports = {
	// JWT
	JWT_SECRET_KEY: process.env.JWT_SECRET_KEY,
	JWT_REFRESH_SECRET_KEY: process.env.JWT_REFRESH_SECRET_KEY,
	// Telegram
	TELEGRAM_API_KEY: process.env.TELEGRAM_API_KEY,
	TELEGRAM_CHAT_ID: process.env.TELEGRAM_CHAT_ID,
	// RazorPay
	RAZORPAY_KEY_ID: process.env.RAZORPAY_KEY_ID,
	RAZORPAY_KEY_SECRET: process.env.RAZORPAY_KEY_SECRET,
};